---

## This play require the following variable set
##   lambda_function_name: "name of lambda to be instrumented"
##   aws_access_key: the aws access key
##   aws_secret_key: the aws secret key
##   aws_region: the aws region
##   with the new ones below


- name: New Relic Log Ingestion lambda
  cloudformation:
    region: "{{ aws_region }}"
    state: "absent"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    capabilities: ["CAPABILITY_AUTO_EXPAND", "CAPABILITY_IAM"]
    stack_name: "{{ lambda_function_name }}-log-ingestion-stack"
