---

# This play require the following variable set
#   nr_api_key: "<from user config newrelic credential>"
#   nr_admin_api_key: "<from user config newrelic credential>"
#   account_id: "<from user config newrelic credential>"
#   service_display_name: "The entity display_name to create alert for"
#   alert_policy_name: "The policy name to use for the alert"
# The fields below are optionals
#   tags: {"dxOwningTeam":"DemoX","dxEnvironment":"development",...} JSON list of tags

- debug:
    msg: "Deploying alerts for {{ service_display_name }} using Terraform for policy {{ alert_policy_name }}"

- fail:
    msg: "nr_api_key is required. Create this entry in your user config file"
  when: nr_api_key is not defined
- fail:
    msg: "nr_admin_api_key is required. Create this entry in your user config file"
  when: nr_admin_api_key is not defined
- fail:
    msg: "account_id is required. Create this entry in your user config file"
  when: account_id is not defined
- fail:
    msg: "alert_policy_name is required. Define this in your deploy config file as a params key/value pair"
  when: alert_policy_name is not defined

- block:
  - name: Creating terraform var file
    set_fact:
      tfvars_json: "{{ tfvars_json | combine({
        'api_key': nr_api_key,
        'admin_api_key': nr_admin_api_key,
        'account_id': account_id,
        'app_name': service_display_name,
        'alert_policy_name': alert_policy_name
        })
      }}"

  - name: "write terraform var to file {{playbook_dir}}/tfvars.json"
    copy:
      content: "{{ tfvars_json | to_nice_json }}"
      dest: "{{ playbook_dir }}/tfvars.json"
  delegate_to: localhost

- fail:
    msg: "WIP stopping here for now"
