---

- fail:
    msg: "newrelic_license_key is required for Configuring NewRelic Infrastructure Agent"
  when: newrelic_license_key is not defined

- debug:
    msg: Configuring NR Infrastructure agent

- block:
  - name: create infra config file
    template:
      src: newrelic-infra.yml
      dest: /etc/newrelic-infra.yml

  - name: Add tags header
    lineinfile:
      path: "/etc/newrelic-infra.yml"
      line: "  {{item.key}}: {{item.value}}"
      insertafter: 'custom_attributes:'
    loop: "{{ (tags|default({}))|dict2items }}"
    when: tags is defined

  - name: Add newrelic infra collector url for infrastructure
    lineinfile:
      path: "/etc/newrelic-infra.yml"
      line: "collector_url: {{ newrelic_infra_collector_url }}"
      insertafter: 'license_key:'
    when: newrelic_infra_collector_url is defined

  - name: Add newrelic infra command url for infrastructure
    lineinfile:
      path: "/etc/newrelic-infra.yml"
      line: "command_channel_url: {{ newrelic_infra_command_url }}"
      insertafter: 'license_key:'
    when: newrelic_infra_command_url is defined

  - name: Add newrelic identity url for infrastructure
    lineinfile:
      path: "/etc/newrelic-infra.yml"
      line: "identity_url: {{ newrelic_identity_url }}"
      insertafter: 'license_key:'
    when: newrelic_identity_url is defined

  become: yes
